"""Pydantic models for the wiring diagram spec format.

The LLM generates a DiagramSpec JSON object; the renderer consumes it.
"""

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field


class Terminal(BaseModel):
    """A connection point on a component."""

    id: str = Field(..., description="Terminal number/name (e.g., '1', 'A1', 'U1', 'PE')")
    label: str = Field(default="", description="Functional label (e.g., 'Line', 'Load', 'Coil+')")
    side: str = Field(default="top", description="Which side: top, bottom, left, right")


class Ratings(BaseModel):
    """Electrical ratings for a component."""

    voltage: Optional[str] = None
    current: Optional[str] = None
    power: Optional[str] = None
    frequency: Optional[str] = None
    protection: Optional[str] = None


class Component(BaseModel):
    """A device on the diagram (contactor, breaker, motor, etc.)."""

    tag: str = Field(..., description="Device designation (Q1, K1, M1, S1, F1, etc.)")
    type: str = Field(
        ...,
        description=(
            "Component type from symbol library: motor_3ph, motor_1ph, "
            "contactor_3pole, contactor_coil, overload_relay, "
            "circuit_breaker, fuse, pushbutton_no, pushbutton_nc, "
            "emergency_stop, terminal_block, plc_input_card, plc_output_card, "
            "vfd, transformer, indicator_light, proximity_sensor, relay_coil, "
            "relay_contact_no, relay_contact_nc"
        ),
    )
    label: str = Field(default="", description="Human-readable name")
    ratings: Optional[Ratings] = None
    terminals: list[Terminal] = Field(default_factory=list)
    group: str = Field(default="main", description="Logical group for layout")
    position_hint: Optional[str] = Field(
        default=None,
        description="Placement hint: top, bottom, left, right, or 'row:col' grid coords",
    )


class Connection(BaseModel):
    """A wire between two terminals."""

    from_terminal: str = Field(
        ..., alias="from", description="Source as 'tag.terminal' (e.g., 'Q1.2')"
    )
    to_terminal: str = Field(
        ..., alias="to", description="Destination as 'tag.terminal' (e.g., 'K1.A1')"
    )
    wire_label: str = Field(default="", description="Wire number/label (W1, L1, +24V)")
    wire_type: str = Field(
        default="power",
        description="Wire type: power, control, signal, earth, neutral",
    )
    gauge: Optional[str] = Field(default=None, description="Wire gauge (e.g., '2.5mm²')")

    class Config:
        populate_by_name = True


class Bus(BaseModel):
    """A power rail or bus bar."""

    name: str = Field(..., description="Bus label (L1, L2, L3, PE, +24V, 0V, N)")
    type: str = Field(default="power", description="Bus type: power, control, earth, neutral")
    orientation: str = Field(default="horizontal", description="horizontal or vertical")


class LayoutHints(BaseModel):
    """Optional layout configuration."""

    power_flow: str = Field(default="top-to-bottom", description="Power flow direction")
    control_flow: str = Field(default="left-to-right", description="Control flow direction")


class DiagramSpec(BaseModel):
    """Complete wiring diagram specification.

    Generated by the LLM from natural language; consumed by WiringRenderer.
    """

    title: str = Field(..., description="Drawing title")
    drawing_number: str = Field(default="FLM-WD-000", description="Unique drawing ID")
    revision: str = Field(default="A")
    author: str = Field(default="Jarvis")
    date: str = Field(default="")
    standard: str = Field(default="IEC", description="IEC or ANSI")
    sheet: str = Field(default="1 of 1")
    description: str = Field(default="", description="Brief description for legend")
    notes: list[str] = Field(default_factory=list)

    components: list[Component] = Field(default_factory=list)
    connections: list[Connection] = Field(default_factory=list)
    buses: list[Bus] = Field(default_factory=list)
    layout: LayoutHints = Field(default_factory=LayoutHints)
